version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: BackendDB
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - 5430:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
      - postgres
    ports:
      - 8000:80
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
