version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./://home/yuriy/
    ports:
      - '8888:8888'
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: admin